### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by oynomed** [z3n70/Frida-Script-Runner#2]
Got an error when I exxecute the script, see screenshot
https://i.imgur.com/7FztVNe.png

**Comment by z3n70** [comment]
Btw your success installation all module bro ? 

Maybe can u try

pip3.11 install subprocess
pip3.11 install os

**Comment by oynomed** [comment]
my python version is Python 3.12.1 and pip version is pip 23.3.2, i'm using windows 10, I already install the requirements and still got error.
I also install the requirements without problem, see screenshots
https://i.imgur.com/D9pcWwW.png

The command above dont work, see screenshots
https://i.imgur.com/zpRRoqQ.png

**Comment by z3n70** [comment]
oke wait i will solve this problem

**Comment by z3n70** [comment]
bro, can u try then clone again this repo and run pip install btw i'm running in windows no error maybe this error your python bro

**Comment by z3n70** [comment]
i running with python 3.11.x

![image](https://github.com/z3n70/Frida-Script-Runner/assets/39817707/bcba2951-d13a-4a88-83f2-59628c27db00)
![image](https://github.com/z3n70/Frida-Script-Runner/assets/39817707/e0053fa7-6d87-4a3b-b979-9bbbc1dbcf0b)



but if i run with python 3.12.x error
![image](https://github.com/z3n70/Frida-Script-Runner/assets/39817707/a9e593c9-8052-45cb-b108-ad315321fb84)

**Comment by oynomed** [comment]
Yes, its working now bro, thanks...

BTW bro, I'm using the latest frida version 16.1.10 and I got this error
https://i.imgur.com/pWxKneD.png

I am using MEMUPLAY EMULATOR, which emulator you recommend to use.

**Comment by z3n70** [comment]
i'm running with genymotion emulator and i not found problem, and i recommend u use real device bro :D, if u not have real device u can use genymotion emulator

<img width="1280" alt="Screen Shot 2023-12-30 at 16 21 53" src="https://github.com/z3n70/Frida-Script-Runner/assets/39817707/a3343416-2c72-4b09-abd4-f6071ec1f2b8">

<img width="1276" alt="Screen Shot 2023-12-30 at 16 28 11" src="https://github.com/z3n70/Frida-Script-Runner/assets/39817707/5399962e-fa6a-4d35-a08c-f56514abc33e">

**Comment by oynomed** [comment]
ok bro, thanks..

**Comment by z3n70** [comment]
Thanks correction for this repo bro
