### ISSUE TITLE
mac os run error???

### ISSUE THREAD

**Issue by pullghjunkkk** [z3n70/Frida-Script-Runner#31]
paulchikkkk@bb6699 ~ % cd Frida-Script-Runner
paulchikkkk@bb6699 Frida-Script-Runner % pip3 install -r requirements.txt

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: /usr/local/opt/python@3.13/bin/python3.13 -m pip install --upgrade pip
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:
    
    python3 -m venv path/to/venv
    source path/to/venv/bin/activate
    python3 -m pip install xyz
    
    If you wish to install a Python application that isn't in Homebrew,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. You can install pipx with
    
    brew install pipx
    
    You may restore the old behavior of pip by passing
    the '--break-system-packages' flag to pip, or by adding
    'break-system-packages = true' to your pip.conf file. The latter
    will permanently disable this error.
    
    If you disable this error, we STRONGLY recommend that you additionally
    pass the '--user' flag to pip, or set 'user = true' in your pip.conf
    file. Failure to do this can result in a broken Homebrew installation.
    
    Read more about this behavior here: <https://peps.python.org/pep-0668/>

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
paulchikkkk@bb6699 Frida-Script-Runner % python3.11 frida_script.py

Traceback (most recent call last):
  File "/Users/paulchikkkk/Frida-Script-Runner/frida_script.py", line 2, in <module>
    from flask_socketio import SocketIO
ModuleNotFoundError: No module named 'flask_socketio'
paulchikkkk@bb6699 Frida-Script-Runner %

**Comment by z3n70** [comment]
i think this error about your python, how many python are on your mac?

**Comment by corrosive4354** [comment]
Because you installed Python using Homebrew, and the system does not allow packages to be installed directly in the global environment.

I think you can try the [servbay](servbay.com) tool, which is more professional on Mac and supports more than homebrew.
